version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Rubens2024!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - mynetwork

  tarefasapp:
    container_name: tarefasapp
    build:
      context: .
      dockerfile: ./TarefasApp.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - mongodb
      - rabbitmq
    networks:
      - mynetwork

  angularapp:
    container_name: angularapp
    build:
      context: .
      dockerfile: ./tarefasweb/Dockerfile
    ports:
      - "4200:4200"
    networks:
      - mynetwork
    volumes:
      - /f/Projetos_CSharp/Thunders/tarefasweb/nginx.conf:/etc/nginx/nginx.conf

volumes:
  sqlserver_data:
  mongodb_data:

networks:
  mynetwork:
    driver: bridge
